/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  docs: [
    'index',
    'dashboard',
    'comparison/ai-code-review-tools',
    {
      type: 'category',
      label: 'ユースケース',
      items: [
        'use-cases/use-cases-index',
        'use-cases/enforce-plan-conformance',
        'use-cases/review-design-adrs-upstream',
        'use-cases/suppress-flaky-review-comments',
      ],
    },
    {
      type: 'category',
      label: 'チュートリアル',
      items: [
        'tutorials/getting-started',
        'tutorials/creating-your-first-skill',
        'tutorials/authoring-skills',
        'tutorials/integrating-with-github-actions',
      ],
    },
    {
      type: 'category',
      label: 'ガイド',
      items: [
        'guides/quickstart',
        'guides/faq',
        'guides/adopter-playbook',
        'guides/cost-estimation',
        'guides/github-actions',
        'guides/run-phase-specific-review',
        'guides/validate-skill-schema',
        'guides/debug-skill-routing',
        'guides/use-riverbed-memory',
        'guides/tracing',
        'guides/agents',
        'guides/deploy-docs-vercel',
        'guides/troubleshooting',
        {
          type: 'category',
          label: 'レビューを運用する',
          items: [
            'guides/two-stage-review-gate',
            'guides/repo-wide-review',
            'guides/w-check',
            'guides/use-independent-review-synthesis',
            'guides/track-runs-and-regressions',
            'guides/agent-workflow',
            'guides/team-os-review-context',
            'guides/ai-agent-playbook',
            'guides/figma-to-code',
          ],
        },
        {
          type: 'category',
          label: 'スキルを扱う',
          items: [
            'guides/starter-cookbook',
            'guides/choose-skills',
            'guides/use-skill-packs',
            'guides/representative-skills',
            'guides/add-new-skill',
            'guides/write-a-skill',
            'guides/agent-skills-codex-cli',
            'guides/manage-skills-cli',
          ],
        },
        {
          type: 'category',
          label: 'ガバナンス',
          items: [
            'guides/governance/CONTRIBUTING',
            'guides/governance/WRITING_GUIDE',
            'guides/governance/roadmap-guide',
            'guides/governance/issue-management',
            'guides/governance/skill-policy',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'コントリビューション',
      items: ['contributing/review-checklist'],
    },
    {
      type: 'category',
      label: 'リファレンス',
      items: [
        'reference/skill-schema',
        'reference/skill-schema-reference',
        'reference/config-schema',
        'reference/metadata-fields',
        'reference/skill-template',
        'reference/skills-catalog',
        'reference/runner-cli-reference',
        'reference/stable-interfaces',
        'reference/review-policy',
        'reference/review-output-example',
        'reference/riverbed-storage',
        'reference/known-limitations',
        'reference/detector-evaluation-report',
        'reference/how-to-cite',
        'reference/glossary',
        {
          type: 'category',
          label: '出力フォーマットと契約',
          items: [
            'reference/review-artifact',
            'reference/output-format-yaml',
            'reference/output-format-html',
            'reference/loop-convergence-contract',
          ],
        },
        {
          type: 'category',
          label: 'CLI 仕様',
          items: [
            'reference/artifact-input-contract',
            'reference/cli-review-plan-spec',
            'reference/cli-review-exec-spec',
            'reference/cli-review-verify-spec',
            'reference/cli-gc-spec',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '解説',
      items: [
        'explanation/intro',
        'explanation/concept',
        'explanation/judgment-placement',
        'explanation/what-is-river-review',
        'explanation/review-scope',
        'explanation/river-architecture',
        'explanation/design-philosophy',
        'explanation/human-judgment-focus',
        'explanation/upstream-midstream-downstream',
        'explanation/skills',
        'explanation/skill-lifecycle',
        'explanation/progressive-disclosure',
        'explanation/reviewer-lens-taxonomy',
        'explanation/riverbed-memory',
        'explanation/security-model',
        {
          type: 'category',
          label: 'フレームワーク',
          items: [
            'explanation/framework/overview',
            'explanation/framework/principles',
            'explanation/framework/checklist',
            'explanation/framework/security-gauntlet',
            'explanation/framework/formal-methods',
            'explanation/framework/agents-hitl',
            'explanation/framework/conclusion',
          ],
        },
      ],
    },
  ],
};
