// tests/cli-option-consumer-check.test.mjs
//
// #2074 — 受理したオプションが消費されているかを `KNOWN_OPTION_TOKENS` 全件で
// 機械検査する（#2065 やること 2 の引き取り）。
//
// #2065 / PR #2073 は `--base` について、コマンド別 allowlist
// （src/cli.mjs `COMMAND_SCOPED_OPTIONS`）と、宣言した面 / 実際に値を読む
// ファイルの drift 検査（tests/cli-base-option-scope.test.mjs）を入れた。
// どちらも `--base` 専用で、**次に平坦に追加されるオプションが全面で受理され、
// どの面でも値を捨てても、何も落ちなかった**。ここではその穴を全オプションへ
// 広げる。
//
// 仕組みは tests/helpers/cli-option-consumers.mjs にある。要点:
//
//   - 受理と書き込みフィールドは **parseArgs を実際に走らせて** 面ごとに測る。
//   - 読み手は **ハンドラのソース**（src/cli/commands/<command>.mjs と、その
//     import 先）を走査して集める。
//   - 「受理されるが消費されない」(option, surface) の組は、その 2 つから
//     **導出** される。手書きの一覧は正にしない。
//
// 導出結果は tests/fixtures/cli-option-consumers.json に **固定** する
// （snapshot）。この固定が本テストの錠であり、次のどれかが起きると落ちる:
//
//   1. 新しいオプションが平坦に追加され、読まない面でも受理されている
//      （fixture に無い組が導出される）
//   2. ある面が新しくフィールドを読み始めた / 読むのをやめた
//      （`readBy` が動く）
//   3. ある面がオプションを拒否し始めた / 受理し始めた（#2065 のような
//      コマンド別 allowlist の変更。canary 側と二重の錠になる）
//
// 落ちたときの対処は 2 択で、**どちらを選ぶかを PR で明示する**:
//   (a) その面で値を読むようにする、または `COMMAND_SCOPED_OPTIONS` に面の
//       集合を宣言して parse 層で拒否する（挙動変更。canary の CASES /
//       EXPECTED_CONTRACT_COUNTS と pages/reference/runner-cli-reference.md
//       ja/en の更新が必須）
//   (b) 「受理するが読まない」を意図的に残す。fixture を再生成して差分を PR に
//       載せる: `RIVER_UPDATE_OPTION_CONSUMERS=1 node --test tests/cli-option-consumer-check.test.mjs`
//       再生成した fixture は `npx prettier --write` で整える（比較は JSON の内容で行うので
//       整形の違いでは落ちないが、lint-staged が pre-commit で整形する）
//
// ★ 検査の解像度は **コマンド単位**（`skills list --from x` は `skills` の
//   import 先が `fromPath` を読むので「消費」と数える）。サブコマンド単位で
//   割れる穴（#2051 の形）は `COMMAND_SCOPED_OPTIONS` の宣言で閉じ、その宣言は
//   tests/cli-base-option-scope.test.mjs が pin する。限界の全文はヘルパの
//   ヘッダにある。
//
// ★ 自己整合を避けるため、本テストは parseArgs の結果だけを信じず、実際に
//   CLI を起動して **production 経路と突き合わせる**（下の end-to-end 節）:
//   `runs list` / `doctor` の 2 面で、「消費されない」と導出された全オプションを
//   付けても exit code と stdout が付けない場合と一致すること、「拒否」と導出
//   された全オプションが exit 1 になること。

import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test, { after, before, describe } from 'node:test';

import { SURFACE_SUBCOMMANDS, parseArgs } from '../src/cli.mjs';
import { runCliInProcess } from './helpers/cli.mjs';
import {
  MAIN_CONSUMED_FIELDS,
  META_OPTIONS,
  OPTION_SAMPLES,
  deriveOptionConsumerMatrix,
  isAccepted,
  mainReadFields,
  readKnownOptionTokens,
  readPromoteSubcommandsFromSource,
  reclaimOwnEnsembleTmpFiles,
} from './helpers/cli-option-consumers.mjs';
import { PROMOTE_SUBCOMMANDS, SURFACES } from './helpers/cli-surfaces.mjs';
import { cleanupTempDir, createTempDir } from './helpers/temp-dir.mjs';
import { createTempGitRepo } from './helpers/temp-repo.mjs';

const FIXTURE_PATH = fileURLToPath(
  new URL('./fixtures/cli-option-consumers.json', import.meta.url)
);
const UPDATE_FIXTURE = process.env.RIVER_UPDATE_OPTION_CONSUMERS === '1';

/**
 * 「受理されるが消費されない」組の総数。fixture と同じ内容の第 2 の錠で、
 * 表を見なくても挙動変更の総量が PR の diff に現れるようにする
 * （canary の EXPECTED_CONTRACT_COUNTS と同じ役割）。
 *
 * 2026-09-05 実測: 71 オプション × 31 面 = 2201 組のうち受理 862 組、
 * うち消費されない 532 組。#2065 の `--base` は 0（5 面だけ受理し全部読む）。
 */
const EXPECTED_ACCEPTED_UNCONSUMED = 532;

const CLI_ENV = { RIVER_OFFLINE: '1', ANTHROPIC_API_KEY: '', OPENAI_API_KEY: '', NO_COLOR: '1' };

/** parseArgs の stderr ノイズ（拒否メッセージ）を抑えて fn を走らせる。 */
function quietly(fn) {
  const { error, warn } = console;
  console.error = () => {};
  console.warn = () => {};
  try {
    return fn();
  } finally {
    console.error = error;
    console.warn = warn;
  }
}

/** fixture に固定する形へ落とす（cells は情報量が多いので入れない）。 */
function toSnapshot(matrix) {
  const snapshot = {
    $comment:
      'GENERATED by tests/cli-option-consumer-check.test.mjs (#2074) — do not edit by hand. ' +
      'Regenerate: RIVER_UPDATE_OPTION_CONSUMERS=1 node --test tests/cli-option-consumer-check.test.mjs. ' +
      'writes = parsed fields the option sets; readBy = commands (or main) whose handler reads one of them; ' +
      'acceptedUnconsumedOn = surfaces that accept the option and never read its value (flat parser, kept on purpose until scoped).',
  };
  for (const [token, row] of Object.entries(matrix)) {
    snapshot[token] = {
      writes: row.writes,
      readBy: row.readBy,
      acceptedUnconsumedOn: row.acceptedUnconsumedOn,
    };
  }
  return snapshot;
}

describe('#2074 accepted-but-unconsumed option check', () => {
  let tokens;
  let matrix;
  let ensembleDir;
  let maxListenersBackup;

  before(() => {
    // `--ensemble` は parse 時にディレクトリを読み、一時ファイルと process の
    // exit listener を面ごとに 1 つ登録する。面数分の listener で
    // MaxListenersExceededWarning が出るので上限を一時的に上げる。
    maxListenersBackup = process.getMaxListeners();
    process.setMaxListeners(Math.max(maxListenersBackup, SURFACES.length * 2 + 10));
    ensembleDir = createTempDir({ prefix: 'river-2074-ensemble-' });
    writeFileSync(join(ensembleDir, 'a.md'), '# a\n');
    tokens = readKnownOptionTokens();
    matrix = quietly(() => deriveOptionConsumerMatrix({ ensembleDir, tokens }));
  });

  after(() => {
    process.setMaxListeners(maxListenersBackup);
    cleanupTempDir(ensembleDir);
  });

  // -------------------------------------------------------------------------
  // 前提の検証（測定の入力が正しいこと）
  // -------------------------------------------------------------------------
  describe('measurement inputs', () => {
    test('the surface list mirrors SURFACE_SUBCOMMANDS plus the promote vocabulary', () => {
      const expected = [];
      for (const [command, { bare, known }] of SURFACE_SUBCOMMANDS) {
        if (bare) expected.push(command);
        for (const subcommand of known ?? []) expected.push(`${command} ${subcommand}`);
      }
      for (const subcommand of PROMOTE_SUBCOMMANDS) expected.push(`promote ${subcommand}`);
      assert.deepEqual(
        SURFACES.map(({ surface }) => surface).sort(),
        expected.sort(),
        'tests/helpers/cli-surfaces.mjs の面一覧が src/cli.mjs の語彙とずれている'
      );
    });

    test('every surface argv is accepted with no option added (control)', () => {
      for (const { surface, argv } of SURFACES) {
        assert.ok(
          isAccepted(quietly(() => parseArgs(argv))),
          `${surface}: 代表 argv がオプション無しで受理されない（測定の前提が崩れている）`
        );
      }
    });

    test('the token universe is KNOWN_OPTION_TOKENS and nothing is silently skipped', () => {
      assert.ok(tokens.length > 0);
      assert.equal(new Set(tokens).size, tokens.length, '重複トークン');
      const covered = new Set([...Object.keys(matrix), ...META_OPTIONS]);
      assert.deepEqual(
        tokens.filter((t) => !covered.has(t)),
        [],
        '行列に現れないトークンがある'
      );
      assert.deepEqual(
        Object.keys(OPTION_SAMPLES).filter((t) => !tokens.includes(t)),
        [],
        'OPTION_SAMPLES に KNOWN_OPTION_TOKENS に無いトークンがある（削除されたオプションの残骸）'
      );
    });

    test('every option is accepted with a non-empty write on at least one surface', () => {
      // 代表値が parse 層の検証に落ちていると、そのオプションは全面で「拒否」
      // と測られ、消費検査が黙って空振りする。ここで止める。
      for (const [token, row] of Object.entries(matrix)) {
        assert.ok(row.acceptedOn.length > 0, `${token}: どの面でも受理されない（代表値が不正か）`);
        for (const surface of row.acceptedOn) {
          assert.ok(
            row.cells[surface].writes.length > 0,
            `${token} @ ${surface}: 受理されたのにフィールドが書かれていない`
          );
        }
      }
    });

    test('-h / --help only ever write `command` (meta options stay out of the matrix)', () => {
      for (const token of META_OPTIONS) {
        for (const { surface, argv } of SURFACES) {
          const before = quietly(() => parseArgs(argv));
          const after = quietly(() => parseArgs([...argv, token]));
          assert.equal(after.command, 'help', `${token} @ ${surface}`);
          const changed = Object.keys(before).filter(
            (k) => JSON.stringify(before[k]) !== JSON.stringify(after[k])
          );
          assert.deepEqual(changed, ['command'], `${token} @ ${surface}: command 以外を書いた`);
        }
      }
    });

    test('MAIN_CONSUMED_FIELDS are really read by main()', () => {
      const reads = mainReadFields();
      for (const field of Object.keys(MAIN_CONSUMED_FIELDS)) {
        assert.ok(reads.has(field), `main() は parsed.${field} を読んでいない（例外の根拠が失効）`);
      }
    });
  });

  // -------------------------------------------------------------------------
  // 本体: 導出結果の固定
  // -------------------------------------------------------------------------
  describe('derived matrix', () => {
    test('#2065: --base is never accepted where it is not read', () => {
      assert.deepEqual(matrix['--base'].acceptedUnconsumedOn, []);
      assert.deepEqual(matrix['--base'].readBy, ['review', 'run', 'skills']);
    });

    test('the total of accepted-but-unconsumed pairs is pinned', () => {
      const total = Object.values(matrix).reduce(
        (sum, row) => sum + row.acceptedUnconsumedOn.length,
        0
      );
      assert.equal(
        total,
        EXPECTED_ACCEPTED_UNCONSUMED,
        `受理されるが消費されない組の総数が動いた（${EXPECTED_ACCEPTED_UNCONSUMED} → ${total}）。` +
          'fixture の差分を確認し、EXPECTED_ACCEPTED_UNCONSUMED をヘッダの規約に従って更新すること'
      );
    });

    test('every accepted-but-unconsumed pair is listed in the fixture, and nothing else is', () => {
      const derived = toSnapshot(matrix);
      if (UPDATE_FIXTURE) {
        writeFileSync(FIXTURE_PATH, `${JSON.stringify(derived, null, 2)}\n`);
      }
      const pinned = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8'));
      const diffs = [];
      for (const token of new Set([...Object.keys(derived), ...Object.keys(pinned)])) {
        const a = JSON.stringify(derived[token] ?? null);
        const b = JSON.stringify(pinned[token] ?? null);
        if (a !== b) diffs.push(`${token}\n  derived: ${a}\n  pinned:  ${b}`);
      }
      assert.deepEqual(
        diffs,
        [],
        'オプションの受理面 / 読み手が実装からずれた。読む（または COMMAND_SCOPED_OPTIONS で拒否する）か、' +
          '意図的に残すなら RIVER_UPDATE_OPTION_CONSUMERS=1 で fixture を再生成して差分を PR に載せる'
      );
    });
  });

  // -------------------------------------------------------------------------
  // 突合: production 経路（CLI 起動）と一致すること
  // -------------------------------------------------------------------------
  // parseArgs の結果とソース走査だけでは、テストが実装と同じ関数を見ているに
  // 過ぎない。実際に CLI を起動し、「消費されない」と導出された全オプションが
  // 本当に何も変えないこと（exit code と stdout が対照と一致）、「拒否」と導出
  // された全オプションが本当に exit 1 になることを、決定論的に走る 2 面で確かめる。
  describe('end-to-end cross-check against the CLI', () => {
    const E2E_SURFACES = ['runs list', 'doctor'];
    let repoDir;
    let cleanupRepo;
    const controls = new Map();

    before(async () => {
      const { dir, cleanup } = await createTempGitRepo({
        prefix: 'river-2074-e2e-',
        initialFiles: { 'a.txt': 'a\n', 'skills/.gitkeep': '' },
        changedFiles: { 'a.txt': 'a\nb\n' },
      });
      repoDir = dir;
      cleanupRepo = cleanup;
      for (const surface of E2E_SURFACES) {
        const { argv } = SURFACES.find((s) => s.surface === surface);
        controls.set(surface, await runCliInProcess(argv, { cwd: repoDir, env: CLI_ENV }));
      }
    });

    after(async () => {
      if (cleanupRepo) await cleanupRepo();
    });

    test('the control runs exit 0 (the surfaces are usable in the temp repo)', () => {
      for (const surface of E2E_SURFACES) {
        assert.equal(controls.get(surface).code, 0, `${surface}: 対照が exit 0 でない`);
      }
    });

    for (const surface of E2E_SURFACES) {
      test(`\`river ${surface} <option>\`: every unconsumed option leaves exit code and stdout unchanged`, async () => {
        const { argv } = SURFACES.find((s) => s.surface === surface);
        const control = controls.get(surface);
        const checked = [];
        for (const [token, row] of Object.entries(matrix)) {
          if (!row.acceptedUnconsumedOn.includes(surface)) continue;
          const value =
            token === '--ensemble' ? [ensembleDir] : (OPTION_SAMPLES[token]?.value ?? []);
          const pre = OPTION_SAMPLES[token]?.pre ?? [];
          const result = await runCliInProcess([...argv, ...pre, token, ...value], {
            cwd: repoDir,
            env: CLI_ENV,
          });
          // `--ensemble` を main() が同一プロセスで parse すると tmp が exit まで
          // 残る（#2087 finding 3）。parsed は受け取れないので pid で回収する。
          if (token === '--ensemble') reclaimOwnEnsembleTmpFiles();
          assert.equal(result.code, control.code, `${surface} ${token}: exit code が対照と違う`);
          assert.equal(result.stdout, control.stdout, `${surface} ${token}: stdout が対照と違う`);
          checked.push(token);
        }
        assert.ok(
          checked.length > 0,
          `${surface}: 消費されないオプションが 1 つも無い（導出が空振り）`
        );
      });

      test(`\`river ${surface} <option>\`: every rejected option exits 1`, async () => {
        const { argv } = SURFACES.find((s) => s.surface === surface);
        const checked = [];
        for (const [token, row] of Object.entries(matrix)) {
          if (row.cells[surface].status !== 'rejected') continue;
          const value = OPTION_SAMPLES[token]?.value ?? [];
          const result = await runCliInProcess([...argv, token, ...value], {
            cwd: repoDir,
            env: CLI_ENV,
          });
          assert.equal(result.code, 1, `${surface} ${token}: 拒否のはずが exit ${result.code}`);
          checked.push(token);
        }
        assert.ok(
          checked.length > 0,
          `${surface}: 拒否されるオプションが 1 つも無い（導出が空振り）`
        );
      });
    }

    // PROMOTE_SUBCOMMANDS はハンドラの語彙の写し。写しがずれていないことを
    // CLI を起動して pin する（SURFACE_SUBCOMMANDS の mirror pin と同じ形）。
    const PROMOTE_USAGE_MARKER = 'Error: usage: river promote';

    test('`river promote nosuch` reports the usage error (marker is live)', async () => {
      const result = await runCliInProcess(['promote', 'nosuch'], { cwd: repoDir, env: CLI_ENV });
      assert.equal(result.code, 1);
      assert.ok(result.stderr.includes(PROMOTE_USAGE_MARKER), result.stderr.slice(0, 300));
    });

    // 上の起動 pin は「写しにある語が実在する」方向だけを守る。src 側に語が
    // 増えても落ちないので（#2087 finding 1）、ハンドラのソースから語彙を読み
    // 両方向で突き合わせる（`readKnownOptionTokens` と同型）。
    test('PROMOTE_SUBCOMMANDS equals the includes([...]) list in promote.mjs (both directions)', () => {
      const fromSource = readPromoteSubcommandsFromSource();
      assert.ok(fromSource.length > 0, 'promote.mjs から語彙が 1 つも読めない');
      assert.deepEqual(
        [...PROMOTE_SUBCOMMANDS].sort(),
        [...fromSource].sort(),
        'tests/helpers/cli-surfaces.mjs PROMOTE_SUBCOMMANDS と src/cli/commands/promote.mjs の語彙がずれている'
      );
    });

    for (const subcommand of PROMOTE_SUBCOMMANDS) {
      test(`\`river promote ${subcommand}\` is a real subcommand (mirror pin)`, async () => {
        const result = await runCliInProcess(['promote', subcommand], {
          cwd: repoDir,
          env: CLI_ENV,
        });
        assert.ok(
          !result.stderr.includes(PROMOTE_USAGE_MARKER),
          `PROMOTE_SUBCOMMANDS がハンドラの語彙からずれている（${subcommand} が未知扱い）。stderr: ${result.stderr.slice(0, 300)}`
        );
      });
    }
  });
});
